//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeplerBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Applications
    {
        public Applications()
        {
            this.SpaceshipTasks = new HashSet<SpaceshipTasks>();
        }
    
        public int ApplicationID { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<SpaceshipTasks> SpaceshipTasks { get; set; }
    }
}
