//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeplerBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class CelesticalBodySystems
    {
        public CelesticalBodySystems()
        {
            this.Orbits = new HashSet<Orbits>();
        }
    
        public int ID { get; set; }
        public Nullable<int> CentralBody_ID { get; set; }
    
        public virtual CelestialBodyBases CelestialBodyBases { get; set; }
        public virtual ICollection<Orbits> Orbits { get; set; }
    }
}
