//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeplerBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Countries
    {
        public Countries()
        {
            this.SpaceShip = new HashSet<SpaceShip>();
        }
    
        public int ID { get; set; }
        public string ISO_3166_1_Key { get; set; }
        public string Description { get; set; }
    
        public virtual ICollection<SpaceShip> SpaceShip { get; set; }
    }
}
