//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeplerBI
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KeplerBIEntities : DbContext
    {
        public KeplerBIEntities()
            : base("name=KeplerBIEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Applications> Applications { get; set; }
        public virtual DbSet<Asteroids> Asteroids { get; set; }
        public virtual DbSet<BigBangs> BigBangs { get; set; }
        public virtual DbSet<CelestialBodyBases> CelestialBodyBases { get; set; }
        public virtual DbSet<CelesticalBodySystems> CelesticalBodySystems { get; set; }
        public virtual DbSet<Comets> Comets { get; set; }
        public virtual DbSet<Countries> Countries { get; set; }
        public virtual DbSet<Galaxies> Galaxies { get; set; }
        public virtual DbSet<GalaxyCores> GalaxyCores { get; set; }
        public virtual DbSet<MannedSpacecraft> MannedSpacecraft { get; set; }
        public virtual DbSet<Moons> Moons { get; set; }
        public virtual DbSet<NCBs> NCBs { get; set; }
        public virtual DbSet<Orbits> Orbits { get; set; }
        public virtual DbSet<Planets> Planets { get; set; }
        public virtual DbSet<SpaceShip> SpaceShip { get; set; }
        public virtual DbSet<SpaceshipTasks> SpaceshipTasks { get; set; }
        public virtual DbSet<Stars> Stars { get; set; }
    }
}
