//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeplerBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class NCBs
    {
        public int ID { get; set; }
        public double MassInEarthmasses { get; set; }
        public double MeanSurfaceTemp { get; set; }
        public double GravityInMeterPerSec { get; set; }
        public double PolarDiameterInKilometer { get; set; }
        public double EquatorialDiameterInKilometer { get; set; }
    
        public virtual Asteroids Asteroids { get; set; }
        public virtual BigBangs BigBangs { get; set; }
        public virtual CelestialBodyBases CelestialBodyBases { get; set; }
        public virtual Comets Comets { get; set; }
        public virtual Galaxies Galaxies { get; set; }
        public virtual GalaxyCores GalaxyCores { get; set; }
        public virtual Moons Moons { get; set; }
        public virtual Planets Planets { get; set; }
        public virtual Stars Stars { get; set; }
    }
}
