//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeplerBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orbits
    {
        public int ID { get; set; }
        public double SemiMajorAxisInKilometer { get; set; }
        public double MeanVelocitiOfCirculationInKmPerSec { get; set; }
        public Nullable<int> Satellite_ID { get; set; }
        public Nullable<int> CelesticalBodySystem_ID { get; set; }
    
        public virtual CelestialBodyBases CelestialBodyBases { get; set; }
        public virtual CelesticalBodySystems CelesticalBodySystems { get; set; }
    }
}
