//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeplerBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaceShip
    {
        public SpaceShip()
        {
            this.SpaceshipTasks = new HashSet<SpaceshipTasks>();
        }
    
        public int ID { get; set; }
        public Nullable<int> Homeland_ID { get; set; }
        public double MassInKg { get; set; }
    
        public virtual CelestialBodyBases CelestialBodyBases { get; set; }
        public virtual Countries Countries { get; set; }
        public virtual MannedSpacecraft MannedSpacecraft { get; set; }
        public virtual ICollection<SpaceshipTasks> SpaceshipTasks { get; set; }
    }
}
