//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeplerBI
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaceshipTasks
    {
        public int ID { get; set; }
        public Nullable<int> Application_ApplicationID { get; set; }
        public Nullable<int> SpaceShip_ID { get; set; }
    
        public virtual Applications Applications { get; set; }
        public virtual SpaceShip SpaceShip { get; set; }
    }
}
