//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// Ursprünglicher Dateiname:
// Erstellungsdatum: 05.06.2014 01:04:00
namespace WcfDataServiceHost.Test.ServiceReference1
{
    
    /// <summary>
    /// Im Schema sind keine Kommentare für "KeplerDBEntities" vorhanden.
    /// </summary>
    public partial class KeplerDBEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialisiert ein neues KeplerDBEntities-Objekt.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public KeplerDBEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot, global::System.Data.Services.Common.DataServiceProtocolVersion.V3)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Da sich der Namespace, der für diesen Dienstverweis in
        /// Visual Studio konfiguriert ist, von demjenigen unterscheidet,
        /// der im Server-Schema angegeben ist, verwenden Sie Typemapper,
        /// um Zuordnungen zwischen den beiden vorzunehmen.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("KeplerDBModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("WcfDataServiceHost.Test.ServiceReference1", typeName.Substring(13)), false);
            }
            return null;
        }
        /// <summary>
        /// Da sich der Namespace, der für diesen Dienstverweis in
        /// Visual Studio konfiguriert ist, von demjenigen unterscheidet,
        /// der im Server-Schema angegeben ist, verwenden Sie Typemapper,
        /// um Zuordnungen zwischen den beiden vorzunehmen.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("WcfDataServiceHost.Test.ServiceReference1", global::System.StringComparison.Ordinal))
            {
                return string.Concat("KeplerDBModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für "HimmelskoerperTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<HimmelskoerperTab> HimmelskoerperTab
        {
            get
            {
                if ((this._HimmelskoerperTab == null))
                {
                    this._HimmelskoerperTab = base.CreateQuery<HimmelskoerperTab>("HimmelskoerperTab");
                }
                return this._HimmelskoerperTab;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<HimmelskoerperTab> _HimmelskoerperTab;
        /// <summary>
        /// Im Schema sind keine Kommentare für "HimmelskoerperTypenTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<HimmelskoerperTypenTab> HimmelskoerperTypenTab
        {
            get
            {
                if ((this._HimmelskoerperTypenTab == null))
                {
                    this._HimmelskoerperTypenTab = base.CreateQuery<HimmelskoerperTypenTab>("HimmelskoerperTypenTab");
                }
                return this._HimmelskoerperTypenTab;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<HimmelskoerperTypenTab> _HimmelskoerperTypenTab;
        /// <summary>
        /// Im Schema sind keine Kommentare für "LaenderTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<LaenderTab> LaenderTab
        {
            get
            {
                if ((this._LaenderTab == null))
                {
                    this._LaenderTab = base.CreateQuery<LaenderTab>("LaenderTab");
                }
                return this._LaenderTab;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<LaenderTab> _LaenderTab;
        /// <summary>
        /// Im Schema sind keine Kommentare für "RaumschiffAufgabenTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RaumschiffAufgabenTab> RaumschiffAufgabenTab
        {
            get
            {
                if ((this._RaumschiffAufgabenTab == null))
                {
                    this._RaumschiffAufgabenTab = base.CreateQuery<RaumschiffAufgabenTab>("RaumschiffAufgabenTab");
                }
                return this._RaumschiffAufgabenTab;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RaumschiffAufgabenTab> _RaumschiffAufgabenTab;
        /// <summary>
        /// Im Schema sind keine Kommentare für "RaumschiffeTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<RaumschiffeTab> RaumschiffeTab
        {
            get
            {
                if ((this._RaumschiffeTab == null))
                {
                    this._RaumschiffeTab = base.CreateQuery<RaumschiffeTab>("RaumschiffeTab");
                }
                return this._RaumschiffeTab;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<RaumschiffeTab> _RaumschiffeTab;
        /// <summary>
        /// Im Schema sind keine Kommentare für "Sterne_Planeten_MondeTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<Sterne_Planeten_MondeTab> Sterne_Planeten_MondeTab
        {
            get
            {
                if ((this._Sterne_Planeten_MondeTab == null))
                {
                    this._Sterne_Planeten_MondeTab = base.CreateQuery<Sterne_Planeten_MondeTab>("Sterne_Planeten_MondeTab");
                }
                return this._Sterne_Planeten_MondeTab;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<Sterne_Planeten_MondeTab> _Sterne_Planeten_MondeTab;
        /// <summary>
        /// Im Schema sind keine Kommentare für "UmlaufbahnenTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<UmlaufbahnenTab> UmlaufbahnenTab
        {
            get
            {
                if ((this._UmlaufbahnenTab == null))
                {
                    this._UmlaufbahnenTab = base.CreateQuery<UmlaufbahnenTab>("UmlaufbahnenTab");
                }
                return this._UmlaufbahnenTab;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<UmlaufbahnenTab> _UmlaufbahnenTab;
        /// <summary>
        /// Im Schema sind keine Kommentare für "UrlSammlungenTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<UrlSammlungenTab> UrlSammlungenTab
        {
            get
            {
                if ((this._UrlSammlungenTab == null))
                {
                    this._UrlSammlungenTab = base.CreateQuery<UrlSammlungenTab>("UrlSammlungenTab");
                }
                return this._UrlSammlungenTab;
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<UrlSammlungenTab> _UrlSammlungenTab;
        /// <summary>
        /// Im Schema sind keine Kommentare für "HimmelskoerperTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToHimmelskoerperTab(HimmelskoerperTab himmelskoerperTab)
        {
            base.AddObject("HimmelskoerperTab", himmelskoerperTab);
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für "HimmelskoerperTypenTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToHimmelskoerperTypenTab(HimmelskoerperTypenTab himmelskoerperTypenTab)
        {
            base.AddObject("HimmelskoerperTypenTab", himmelskoerperTypenTab);
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für "LaenderTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToLaenderTab(LaenderTab laenderTab)
        {
            base.AddObject("LaenderTab", laenderTab);
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für "RaumschiffAufgabenTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRaumschiffAufgabenTab(RaumschiffAufgabenTab raumschiffAufgabenTab)
        {
            base.AddObject("RaumschiffAufgabenTab", raumschiffAufgabenTab);
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für "RaumschiffeTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToRaumschiffeTab(RaumschiffeTab raumschiffeTab)
        {
            base.AddObject("RaumschiffeTab", raumschiffeTab);
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für "Sterne_Planeten_MondeTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToSterne_Planeten_MondeTab(Sterne_Planeten_MondeTab sterne_Planeten_MondeTab)
        {
            base.AddObject("Sterne_Planeten_MondeTab", sterne_Planeten_MondeTab);
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für "UmlaufbahnenTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUmlaufbahnenTab(UmlaufbahnenTab umlaufbahnenTab)
        {
            base.AddObject("UmlaufbahnenTab", umlaufbahnenTab);
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für "UrlSammlungenTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToUrlSammlungenTab(UrlSammlungenTab urlSammlungenTab)
        {
            base.AddObject("UrlSammlungenTab", urlSammlungenTab);
        }
    }
    /// <summary>
    /// Im Schema sind keine Kommentare für "KeplerDBModel.HimmelskoerperTab" vorhanden.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("HimmelskoerperTab")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class HimmelskoerperTab : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues HimmelskoerperTab-Objekt.
        /// </summary>
        /// <param name="ID">Anfangswert von ID.</param>
        /// <param name="name">Anfangswert von Name.</param>
        /// <param name="masse_in_kg">Anfangswert von Masse_in_kg.</param>
        /// <param name="himmelskoerperTyp_ID">Anfangswert von HimmelskoerperTyp_ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static HimmelskoerperTab CreateHimmelskoerperTab(int ID, string name, double masse_in_kg, int himmelskoerperTyp_ID)
        {
            HimmelskoerperTab himmelskoerperTab = new HimmelskoerperTab();
            himmelskoerperTab.ID = ID;
            himmelskoerperTab.Name = name;
            himmelskoerperTab.Masse_in_kg = masse_in_kg;
            himmelskoerperTab.HimmelskoerperTyp_ID = himmelskoerperTyp_ID;
            return himmelskoerperTab;
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "ID" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Name" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Masse_in_kg" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Masse_in_kg
        {
            get
            {
                return this._Masse_in_kg;
            }
            set
            {
                this.OnMasse_in_kgChanging(value);
                this._Masse_in_kg = value;
                this.OnMasse_in_kgChanged();
                this.OnPropertyChanged("Masse_in_kg");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Masse_in_kg;
        partial void OnMasse_in_kgChanging(double value);
        partial void OnMasse_in_kgChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "HimmelskoerperTyp_ID" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int HimmelskoerperTyp_ID
        {
            get
            {
                return this._HimmelskoerperTyp_ID;
            }
            set
            {
                this.OnHimmelskoerperTyp_IDChanging(value);
                this._HimmelskoerperTyp_ID = value;
                this.OnHimmelskoerperTyp_IDChanged();
                this.OnPropertyChanged("HimmelskoerperTyp_ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _HimmelskoerperTyp_ID;
        partial void OnHimmelskoerperTyp_IDChanging(int value);
        partial void OnHimmelskoerperTyp_IDChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für "HimmelskoerperTypenTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public HimmelskoerperTypenTab HimmelskoerperTypenTab
        {
            get
            {
                return this._HimmelskoerperTypenTab;
            }
            set
            {
                this._HimmelskoerperTypenTab = value;
                this.OnPropertyChanged("HimmelskoerperTypenTab");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private HimmelskoerperTypenTab _HimmelskoerperTypenTab;
        /// <summary>
        /// Im Schema sind keine Kommentare für "RaumschiffeTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RaumschiffeTab> RaumschiffeTab
        {
            get
            {
                return this._RaumschiffeTab;
            }
            set
            {
                this._RaumschiffeTab = value;
                this.OnPropertyChanged("RaumschiffeTab");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RaumschiffeTab> _RaumschiffeTab = new global::System.Data.Services.Client.DataServiceCollection<RaumschiffeTab>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// Im Schema sind keine Kommentare für "Sterne_Planeten_MondeTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<Sterne_Planeten_MondeTab> Sterne_Planeten_MondeTab
        {
            get
            {
                return this._Sterne_Planeten_MondeTab;
            }
            set
            {
                this._Sterne_Planeten_MondeTab = value;
                this.OnPropertyChanged("Sterne_Planeten_MondeTab");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<Sterne_Planeten_MondeTab> _Sterne_Planeten_MondeTab = new global::System.Data.Services.Client.DataServiceCollection<Sterne_Planeten_MondeTab>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// Im Schema sind keine Kommentare für "UrlSammlungenTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<UrlSammlungenTab> UrlSammlungenTab
        {
            get
            {
                return this._UrlSammlungenTab;
            }
            set
            {
                this._UrlSammlungenTab = value;
                this.OnPropertyChanged("UrlSammlungenTab");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<UrlSammlungenTab> _UrlSammlungenTab = new global::System.Data.Services.Client.DataServiceCollection<UrlSammlungenTab>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// Im Schema sind keine Kommentare für "UmlaufbahnenTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<UmlaufbahnenTab> UmlaufbahnenTab
        {
            get
            {
                return this._UmlaufbahnenTab;
            }
            set
            {
                this._UmlaufbahnenTab = value;
                this.OnPropertyChanged("UmlaufbahnenTab");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<UmlaufbahnenTab> _UmlaufbahnenTab = new global::System.Data.Services.Client.DataServiceCollection<UmlaufbahnenTab>(null, global::System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// Im Schema sind keine Kommentare für "UmlaufbahnenTab1" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<UmlaufbahnenTab> UmlaufbahnenTab1
        {
            get
            {
                return this._UmlaufbahnenTab1;
            }
            set
            {
                this._UmlaufbahnenTab1 = value;
                this.OnPropertyChanged("UmlaufbahnenTab1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<UmlaufbahnenTab> _UmlaufbahnenTab1 = new global::System.Data.Services.Client.DataServiceCollection<UmlaufbahnenTab>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Im Schema sind keine Kommentare für "KeplerDBModel.HimmelskoerperTypenTab" vorhanden.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("HimmelskoerperTypenTab")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class HimmelskoerperTypenTab : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues HimmelskoerperTypenTab-Objekt.
        /// </summary>
        /// <param name="ID">Anfangswert von ID.</param>
        /// <param name="name">Anfangswert von Name.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static HimmelskoerperTypenTab CreateHimmelskoerperTypenTab(int ID, string name)
        {
            HimmelskoerperTypenTab himmelskoerperTypenTab = new HimmelskoerperTypenTab();
            himmelskoerperTypenTab.ID = ID;
            himmelskoerperTypenTab.Name = name;
            return himmelskoerperTypenTab;
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "ID" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Name" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für "HimmelskoerperTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<HimmelskoerperTab> HimmelskoerperTab
        {
            get
            {
                return this._HimmelskoerperTab;
            }
            set
            {
                this._HimmelskoerperTab = value;
                this.OnPropertyChanged("HimmelskoerperTab");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<HimmelskoerperTab> _HimmelskoerperTab = new global::System.Data.Services.Client.DataServiceCollection<HimmelskoerperTab>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Im Schema sind keine Kommentare für "KeplerDBModel.LaenderTab" vorhanden.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("LaenderTab")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class LaenderTab : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues LaenderTab-Objekt.
        /// </summary>
        /// <param name="ID">Anfangswert von ID.</param>
        /// <param name="name">Anfangswert von Name.</param>
        /// <param name="laenderkennzeichen">Anfangswert von Laenderkennzeichen.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static LaenderTab CreateLaenderTab(int ID, string name, string laenderkennzeichen)
        {
            LaenderTab laenderTab = new LaenderTab();
            laenderTab.ID = ID;
            laenderTab.Name = name;
            laenderTab.Laenderkennzeichen = laenderkennzeichen;
            return laenderTab;
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "ID" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Name" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Name
        {
            get
            {
                return this._Name;
            }
            set
            {
                this.OnNameChanging(value);
                this._Name = value;
                this.OnNameChanged();
                this.OnPropertyChanged("Name");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Name;
        partial void OnNameChanging(string value);
        partial void OnNameChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Laenderkennzeichen" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Laenderkennzeichen
        {
            get
            {
                return this._Laenderkennzeichen;
            }
            set
            {
                this.OnLaenderkennzeichenChanging(value);
                this._Laenderkennzeichen = value;
                this.OnLaenderkennzeichenChanged();
                this.OnPropertyChanged("Laenderkennzeichen");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Laenderkennzeichen;
        partial void OnLaenderkennzeichenChanging(string value);
        partial void OnLaenderkennzeichenChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für "RaumschiffeTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RaumschiffeTab> RaumschiffeTab
        {
            get
            {
                return this._RaumschiffeTab;
            }
            set
            {
                this._RaumschiffeTab = value;
                this.OnPropertyChanged("RaumschiffeTab");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RaumschiffeTab> _RaumschiffeTab = new global::System.Data.Services.Client.DataServiceCollection<RaumschiffeTab>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Im Schema sind keine Kommentare für "KeplerDBModel.RaumschiffAufgabenTab" vorhanden.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("RaumschiffAufgabenTab")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class RaumschiffAufgabenTab : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues RaumschiffAufgabenTab-Objekt.
        /// </summary>
        /// <param name="ID">Anfangswert von ID.</param>
        /// <param name="aufgabenbeschreibung">Anfangswert von Aufgabenbeschreibung.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RaumschiffAufgabenTab CreateRaumschiffAufgabenTab(int ID, string aufgabenbeschreibung)
        {
            RaumschiffAufgabenTab raumschiffAufgabenTab = new RaumschiffAufgabenTab();
            raumschiffAufgabenTab.ID = ID;
            raumschiffAufgabenTab.Aufgabenbeschreibung = aufgabenbeschreibung;
            return raumschiffAufgabenTab;
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "ID" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Aufgabenbeschreibung" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Aufgabenbeschreibung
        {
            get
            {
                return this._Aufgabenbeschreibung;
            }
            set
            {
                this.OnAufgabenbeschreibungChanging(value);
                this._Aufgabenbeschreibung = value;
                this.OnAufgabenbeschreibungChanged();
                this.OnPropertyChanged("Aufgabenbeschreibung");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Aufgabenbeschreibung;
        partial void OnAufgabenbeschreibungChanging(string value);
        partial void OnAufgabenbeschreibungChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für "RaumschiffeTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<RaumschiffeTab> RaumschiffeTab
        {
            get
            {
                return this._RaumschiffeTab;
            }
            set
            {
                this._RaumschiffeTab = value;
                this.OnPropertyChanged("RaumschiffeTab");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<RaumschiffeTab> _RaumschiffeTab = new global::System.Data.Services.Client.DataServiceCollection<RaumschiffeTab>(null, global::System.Data.Services.Client.TrackingMode.None);
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Im Schema sind keine Kommentare für "KeplerDBModel.RaumschiffeTab" vorhanden.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("RaumschiffeTab")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class RaumschiffeTab : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues RaumschiffeTab-Objekt.
        /// </summary>
        /// <param name="start_der_Mission">Anfangswert von Start_der_Mission.</param>
        /// <param name="ID">Anfangswert von ID.</param>
        /// <param name="himmelskoerper_ID">Anfangswert von Himmelskoerper_ID.</param>
        /// <param name="land_ID">Anfangswert von Land_ID.</param>
        /// <param name="raumschiffAufgaben_ID">Anfangswert von RaumschiffAufgaben_ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static RaumschiffeTab CreateRaumschiffeTab(global::System.DateTime start_der_Mission, int ID, int himmelskoerper_ID, int land_ID, int raumschiffAufgaben_ID)
        {
            RaumschiffeTab raumschiffeTab = new RaumschiffeTab();
            raumschiffeTab.Start_der_Mission = start_der_Mission;
            raumschiffeTab.ID = ID;
            raumschiffeTab.Himmelskoerper_ID = himmelskoerper_ID;
            raumschiffeTab.Land_ID = land_ID;
            raumschiffeTab.RaumschiffAufgaben_ID = raumschiffAufgaben_ID;
            return raumschiffeTab;
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Start_der_Mission" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.DateTime Start_der_Mission
        {
            get
            {
                return this._Start_der_Mission;
            }
            set
            {
                this.OnStart_der_MissionChanging(value);
                this._Start_der_Mission = value;
                this.OnStart_der_MissionChanged();
                this.OnPropertyChanged("Start_der_Mission");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.DateTime _Start_der_Mission;
        partial void OnStart_der_MissionChanging(global::System.DateTime value);
        partial void OnStart_der_MissionChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "ID" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Himmelskoerper_ID" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Himmelskoerper_ID
        {
            get
            {
                return this._Himmelskoerper_ID;
            }
            set
            {
                this.OnHimmelskoerper_IDChanging(value);
                this._Himmelskoerper_ID = value;
                this.OnHimmelskoerper_IDChanged();
                this.OnPropertyChanged("Himmelskoerper_ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Himmelskoerper_ID;
        partial void OnHimmelskoerper_IDChanging(int value);
        partial void OnHimmelskoerper_IDChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Land_ID" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Land_ID
        {
            get
            {
                return this._Land_ID;
            }
            set
            {
                this.OnLand_IDChanging(value);
                this._Land_ID = value;
                this.OnLand_IDChanged();
                this.OnPropertyChanged("Land_ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Land_ID;
        partial void OnLand_IDChanging(int value);
        partial void OnLand_IDChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "RaumschiffAufgaben_ID" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int RaumschiffAufgaben_ID
        {
            get
            {
                return this._RaumschiffAufgaben_ID;
            }
            set
            {
                this.OnRaumschiffAufgaben_IDChanging(value);
                this._RaumschiffAufgaben_ID = value;
                this.OnRaumschiffAufgaben_IDChanged();
                this.OnPropertyChanged("RaumschiffAufgaben_ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _RaumschiffAufgaben_ID;
        partial void OnRaumschiffAufgaben_IDChanging(int value);
        partial void OnRaumschiffAufgaben_IDChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für "HimmelskoerperTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public HimmelskoerperTab HimmelskoerperTab
        {
            get
            {
                return this._HimmelskoerperTab;
            }
            set
            {
                this._HimmelskoerperTab = value;
                this.OnPropertyChanged("HimmelskoerperTab");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private HimmelskoerperTab _HimmelskoerperTab;
        /// <summary>
        /// Im Schema sind keine Kommentare für "LaenderTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public LaenderTab LaenderTab
        {
            get
            {
                return this._LaenderTab;
            }
            set
            {
                this._LaenderTab = value;
                this.OnPropertyChanged("LaenderTab");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private LaenderTab _LaenderTab;
        /// <summary>
        /// Im Schema sind keine Kommentare für "RaumschiffAufgabenTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public RaumschiffAufgabenTab RaumschiffAufgabenTab
        {
            get
            {
                return this._RaumschiffAufgabenTab;
            }
            set
            {
                this._RaumschiffAufgabenTab = value;
                this.OnPropertyChanged("RaumschiffAufgabenTab");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private RaumschiffAufgabenTab _RaumschiffAufgabenTab;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Im Schema sind keine Kommentare für "KeplerDBModel.Sterne_Planeten_MondeTab" vorhanden.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Sterne_Planeten_MondeTab")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class Sterne_Planeten_MondeTab : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues Sterne_Planeten_MondeTab-Objekt.
        /// </summary>
        /// <param name="aequatordurchmesser_in_km">Anfangswert von Aequatordurchmesser_in_km.</param>
        /// <param name="polardurchmesser_in_km">Anfangswert von Polardurchmesser_in_km.</param>
        /// <param name="oberflaechentemperatur_in_K">Anfangswert von Oberflaechentemperatur_in_K.</param>
        /// <param name="rotationsperiode_in_Stunden">Anfangswert von Rotationsperiode_in_Stunden.</param>
        /// <param name="fallbeschleunigung_in_meter_pro_sec">Anfangswert von Fallbeschleunigung_in_meter_pro_sec.</param>
        /// <param name="rotationsachsenneigung_in_Grad">Anfangswert von Rotationsachsenneigung_in_Grad.</param>
        /// <param name="ID">Anfangswert von ID.</param>
        /// <param name="himmelskoerper_ID">Anfangswert von Himmelskoerper_ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static Sterne_Planeten_MondeTab CreateSterne_Planeten_MondeTab(double aequatordurchmesser_in_km, double polardurchmesser_in_km, double oberflaechentemperatur_in_K, double rotationsperiode_in_Stunden, double fallbeschleunigung_in_meter_pro_sec, double rotationsachsenneigung_in_Grad, int ID, int himmelskoerper_ID)
        {
            Sterne_Planeten_MondeTab sterne_Planeten_MondeTab = new Sterne_Planeten_MondeTab();
            sterne_Planeten_MondeTab.Aequatordurchmesser_in_km = aequatordurchmesser_in_km;
            sterne_Planeten_MondeTab.Polardurchmesser_in_km = polardurchmesser_in_km;
            sterne_Planeten_MondeTab.Oberflaechentemperatur_in_K = oberflaechentemperatur_in_K;
            sterne_Planeten_MondeTab.Rotationsperiode_in_Stunden = rotationsperiode_in_Stunden;
            sterne_Planeten_MondeTab.Fallbeschleunigung_in_meter_pro_sec = fallbeschleunigung_in_meter_pro_sec;
            sterne_Planeten_MondeTab.Rotationsachsenneigung_in_Grad = rotationsachsenneigung_in_Grad;
            sterne_Planeten_MondeTab.ID = ID;
            sterne_Planeten_MondeTab.Himmelskoerper_ID = himmelskoerper_ID;
            return sterne_Planeten_MondeTab;
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Aequatordurchmesser_in_km" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Aequatordurchmesser_in_km
        {
            get
            {
                return this._Aequatordurchmesser_in_km;
            }
            set
            {
                this.OnAequatordurchmesser_in_kmChanging(value);
                this._Aequatordurchmesser_in_km = value;
                this.OnAequatordurchmesser_in_kmChanged();
                this.OnPropertyChanged("Aequatordurchmesser_in_km");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Aequatordurchmesser_in_km;
        partial void OnAequatordurchmesser_in_kmChanging(double value);
        partial void OnAequatordurchmesser_in_kmChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Polardurchmesser_in_km" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Polardurchmesser_in_km
        {
            get
            {
                return this._Polardurchmesser_in_km;
            }
            set
            {
                this.OnPolardurchmesser_in_kmChanging(value);
                this._Polardurchmesser_in_km = value;
                this.OnPolardurchmesser_in_kmChanged();
                this.OnPropertyChanged("Polardurchmesser_in_km");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Polardurchmesser_in_km;
        partial void OnPolardurchmesser_in_kmChanging(double value);
        partial void OnPolardurchmesser_in_kmChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Oberflaechentemperatur_in_K" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Oberflaechentemperatur_in_K
        {
            get
            {
                return this._Oberflaechentemperatur_in_K;
            }
            set
            {
                this.OnOberflaechentemperatur_in_KChanging(value);
                this._Oberflaechentemperatur_in_K = value;
                this.OnOberflaechentemperatur_in_KChanged();
                this.OnPropertyChanged("Oberflaechentemperatur_in_K");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Oberflaechentemperatur_in_K;
        partial void OnOberflaechentemperatur_in_KChanging(double value);
        partial void OnOberflaechentemperatur_in_KChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Rotationsperiode_in_Stunden" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Rotationsperiode_in_Stunden
        {
            get
            {
                return this._Rotationsperiode_in_Stunden;
            }
            set
            {
                this.OnRotationsperiode_in_StundenChanging(value);
                this._Rotationsperiode_in_Stunden = value;
                this.OnRotationsperiode_in_StundenChanged();
                this.OnPropertyChanged("Rotationsperiode_in_Stunden");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Rotationsperiode_in_Stunden;
        partial void OnRotationsperiode_in_StundenChanging(double value);
        partial void OnRotationsperiode_in_StundenChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Fallbeschleunigung_in_meter_pro_sec" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Fallbeschleunigung_in_meter_pro_sec
        {
            get
            {
                return this._Fallbeschleunigung_in_meter_pro_sec;
            }
            set
            {
                this.OnFallbeschleunigung_in_meter_pro_secChanging(value);
                this._Fallbeschleunigung_in_meter_pro_sec = value;
                this.OnFallbeschleunigung_in_meter_pro_secChanged();
                this.OnPropertyChanged("Fallbeschleunigung_in_meter_pro_sec");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Fallbeschleunigung_in_meter_pro_sec;
        partial void OnFallbeschleunigung_in_meter_pro_secChanging(double value);
        partial void OnFallbeschleunigung_in_meter_pro_secChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Rotationsachsenneigung_in_Grad" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Rotationsachsenneigung_in_Grad
        {
            get
            {
                return this._Rotationsachsenneigung_in_Grad;
            }
            set
            {
                this.OnRotationsachsenneigung_in_GradChanging(value);
                this._Rotationsachsenneigung_in_Grad = value;
                this.OnRotationsachsenneigung_in_GradChanged();
                this.OnPropertyChanged("Rotationsachsenneigung_in_Grad");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Rotationsachsenneigung_in_Grad;
        partial void OnRotationsachsenneigung_in_GradChanging(double value);
        partial void OnRotationsachsenneigung_in_GradChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "ID" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Himmelskoerper_ID" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Himmelskoerper_ID
        {
            get
            {
                return this._Himmelskoerper_ID;
            }
            set
            {
                this.OnHimmelskoerper_IDChanging(value);
                this._Himmelskoerper_ID = value;
                this.OnHimmelskoerper_IDChanged();
                this.OnPropertyChanged("Himmelskoerper_ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Himmelskoerper_ID;
        partial void OnHimmelskoerper_IDChanging(int value);
        partial void OnHimmelskoerper_IDChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für "HimmelskoerperTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public HimmelskoerperTab HimmelskoerperTab
        {
            get
            {
                return this._HimmelskoerperTab;
            }
            set
            {
                this._HimmelskoerperTab = value;
                this.OnPropertyChanged("HimmelskoerperTab");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private HimmelskoerperTab _HimmelskoerperTab;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Im Schema sind keine Kommentare für "KeplerDBModel.UmlaufbahnenTab" vorhanden.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("UmlaufbahnenTab")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class UmlaufbahnenTab : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues UmlaufbahnenTab-Objekt.
        /// </summary>
        /// <param name="laenge_grosse_Halbachse_in_km">Anfangswert von Laenge_grosse_Halbachse_in_km.</param>
        /// <param name="exzentritzitaet">Anfangswert von Exzentritzitaet.</param>
        /// <param name="umlaufdauer_in_Tagen">Anfangswert von Umlaufdauer_in_Tagen.</param>
        /// <param name="mittlere_Umlaufgeschwindigkeit_in_km_pro_sec">Anfangswert von Mittlere_Umlaufgeschwindigkeit_in_km_pro_sec.</param>
        /// <param name="ID">Anfangswert von ID.</param>
        /// <param name="trabant_ID">Anfangswert von Trabant_ID.</param>
        /// <param name="zentralobjekt_ID">Anfangswert von Zentralobjekt_ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static UmlaufbahnenTab CreateUmlaufbahnenTab(double laenge_grosse_Halbachse_in_km, double exzentritzitaet, double umlaufdauer_in_Tagen, double mittlere_Umlaufgeschwindigkeit_in_km_pro_sec, int ID, int trabant_ID, int zentralobjekt_ID)
        {
            UmlaufbahnenTab umlaufbahnenTab = new UmlaufbahnenTab();
            umlaufbahnenTab.Laenge_grosse_Halbachse_in_km = laenge_grosse_Halbachse_in_km;
            umlaufbahnenTab.Exzentritzitaet = exzentritzitaet;
            umlaufbahnenTab.Umlaufdauer_in_Tagen = umlaufdauer_in_Tagen;
            umlaufbahnenTab.Mittlere_Umlaufgeschwindigkeit_in_km_pro_sec = mittlere_Umlaufgeschwindigkeit_in_km_pro_sec;
            umlaufbahnenTab.ID = ID;
            umlaufbahnenTab.Trabant_ID = trabant_ID;
            umlaufbahnenTab.Zentralobjekt_ID = zentralobjekt_ID;
            return umlaufbahnenTab;
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Laenge_grosse_Halbachse_in_km" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Laenge_grosse_Halbachse_in_km
        {
            get
            {
                return this._Laenge_grosse_Halbachse_in_km;
            }
            set
            {
                this.OnLaenge_grosse_Halbachse_in_kmChanging(value);
                this._Laenge_grosse_Halbachse_in_km = value;
                this.OnLaenge_grosse_Halbachse_in_kmChanged();
                this.OnPropertyChanged("Laenge_grosse_Halbachse_in_km");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Laenge_grosse_Halbachse_in_km;
        partial void OnLaenge_grosse_Halbachse_in_kmChanging(double value);
        partial void OnLaenge_grosse_Halbachse_in_kmChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Exzentritzitaet" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Exzentritzitaet
        {
            get
            {
                return this._Exzentritzitaet;
            }
            set
            {
                this.OnExzentritzitaetChanging(value);
                this._Exzentritzitaet = value;
                this.OnExzentritzitaetChanged();
                this.OnPropertyChanged("Exzentritzitaet");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Exzentritzitaet;
        partial void OnExzentritzitaetChanging(double value);
        partial void OnExzentritzitaetChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Umlaufdauer_in_Tagen" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Umlaufdauer_in_Tagen
        {
            get
            {
                return this._Umlaufdauer_in_Tagen;
            }
            set
            {
                this.OnUmlaufdauer_in_TagenChanging(value);
                this._Umlaufdauer_in_Tagen = value;
                this.OnUmlaufdauer_in_TagenChanged();
                this.OnPropertyChanged("Umlaufdauer_in_Tagen");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Umlaufdauer_in_Tagen;
        partial void OnUmlaufdauer_in_TagenChanging(double value);
        partial void OnUmlaufdauer_in_TagenChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Mittlere_Umlaufgeschwindigkeit_in_km_pro_sec" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public double Mittlere_Umlaufgeschwindigkeit_in_km_pro_sec
        {
            get
            {
                return this._Mittlere_Umlaufgeschwindigkeit_in_km_pro_sec;
            }
            set
            {
                this.OnMittlere_Umlaufgeschwindigkeit_in_km_pro_secChanging(value);
                this._Mittlere_Umlaufgeschwindigkeit_in_km_pro_sec = value;
                this.OnMittlere_Umlaufgeschwindigkeit_in_km_pro_secChanged();
                this.OnPropertyChanged("Mittlere_Umlaufgeschwindigkeit_in_km_pro_sec");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private double _Mittlere_Umlaufgeschwindigkeit_in_km_pro_sec;
        partial void OnMittlere_Umlaufgeschwindigkeit_in_km_pro_secChanging(double value);
        partial void OnMittlere_Umlaufgeschwindigkeit_in_km_pro_secChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "ID" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Trabant_ID" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Trabant_ID
        {
            get
            {
                return this._Trabant_ID;
            }
            set
            {
                this.OnTrabant_IDChanging(value);
                this._Trabant_ID = value;
                this.OnTrabant_IDChanged();
                this.OnPropertyChanged("Trabant_ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Trabant_ID;
        partial void OnTrabant_IDChanging(int value);
        partial void OnTrabant_IDChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Zentralobjekt_ID" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Zentralobjekt_ID
        {
            get
            {
                return this._Zentralobjekt_ID;
            }
            set
            {
                this.OnZentralobjekt_IDChanging(value);
                this._Zentralobjekt_ID = value;
                this.OnZentralobjekt_IDChanged();
                this.OnPropertyChanged("Zentralobjekt_ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Zentralobjekt_ID;
        partial void OnZentralobjekt_IDChanging(int value);
        partial void OnZentralobjekt_IDChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für "HimmelskoerperTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public HimmelskoerperTab HimmelskoerperTab
        {
            get
            {
                return this._HimmelskoerperTab;
            }
            set
            {
                this._HimmelskoerperTab = value;
                this.OnPropertyChanged("HimmelskoerperTab");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private HimmelskoerperTab _HimmelskoerperTab;
        /// <summary>
        /// Im Schema sind keine Kommentare für "HimmelskoerperTab1" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public HimmelskoerperTab HimmelskoerperTab1
        {
            get
            {
                return this._HimmelskoerperTab1;
            }
            set
            {
                this._HimmelskoerperTab1 = value;
                this.OnPropertyChanged("HimmelskoerperTab1");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private HimmelskoerperTab _HimmelskoerperTab1;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Im Schema sind keine Kommentare für "KeplerDBModel.UrlSammlungenTab" vorhanden.
    /// </summary>
    /// <KeyProperties>
    /// ID
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("UrlSammlungenTab")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("ID")]
    public partial class UrlSammlungenTab : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues UrlSammlungenTab-Objekt.
        /// </summary>
        /// <param name="ID">Anfangswert von ID.</param>
        /// <param name="kurzbeschreibung">Anfangswert von Kurzbeschreibung.</param>
        /// <param name="url">Anfangswert von Url.</param>
        /// <param name="urlTyp">Anfangswert von UrlTyp.</param>
        /// <param name="himmelskoerper_ID">Anfangswert von Himmelskoerper_ID.</param>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static UrlSammlungenTab CreateUrlSammlungenTab(int ID, string kurzbeschreibung, string url, int urlTyp, int himmelskoerper_ID)
        {
            UrlSammlungenTab urlSammlungenTab = new UrlSammlungenTab();
            urlSammlungenTab.ID = ID;
            urlSammlungenTab.Kurzbeschreibung = kurzbeschreibung;
            urlSammlungenTab.Url = url;
            urlSammlungenTab.UrlTyp = urlTyp;
            urlSammlungenTab.Himmelskoerper_ID = himmelskoerper_ID;
            return urlSammlungenTab;
        }
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "ID" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int ID
        {
            get
            {
                return this._ID;
            }
            set
            {
                this.OnIDChanging(value);
                this._ID = value;
                this.OnIDChanged();
                this.OnPropertyChanged("ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _ID;
        partial void OnIDChanging(int value);
        partial void OnIDChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Kurzbeschreibung" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Kurzbeschreibung
        {
            get
            {
                return this._Kurzbeschreibung;
            }
            set
            {
                this.OnKurzbeschreibungChanging(value);
                this._Kurzbeschreibung = value;
                this.OnKurzbeschreibungChanged();
                this.OnPropertyChanged("Kurzbeschreibung");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Kurzbeschreibung;
        partial void OnKurzbeschreibungChanging(string value);
        partial void OnKurzbeschreibungChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Url" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string Url
        {
            get
            {
                return this._Url;
            }
            set
            {
                this.OnUrlChanging(value);
                this._Url = value;
                this.OnUrlChanged();
                this.OnPropertyChanged("Url");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _Url;
        partial void OnUrlChanging(string value);
        partial void OnUrlChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "UrlTyp" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int UrlTyp
        {
            get
            {
                return this._UrlTyp;
            }
            set
            {
                this.OnUrlTypChanging(value);
                this._UrlTyp = value;
                this.OnUrlTypChanged();
                this.OnPropertyChanged("UrlTyp");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _UrlTyp;
        partial void OnUrlTypChanging(int value);
        partial void OnUrlTypChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für die Eigenschaft "Himmelskoerper_ID" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int Himmelskoerper_ID
        {
            get
            {
                return this._Himmelskoerper_ID;
            }
            set
            {
                this.OnHimmelskoerper_IDChanging(value);
                this._Himmelskoerper_ID = value;
                this.OnHimmelskoerper_IDChanged();
                this.OnPropertyChanged("Himmelskoerper_ID");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _Himmelskoerper_ID;
        partial void OnHimmelskoerper_IDChanging(int value);
        partial void OnHimmelskoerper_IDChanged();
        /// <summary>
        /// Im Schema sind keine Kommentare für "HimmelskoerperTab" vorhanden.
        /// </summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public HimmelskoerperTab HimmelskoerperTab
        {
            get
            {
                return this._HimmelskoerperTab;
            }
            set
            {
                this._HimmelskoerperTab = value;
                this.OnPropertyChanged("HimmelskoerperTab");
            }
        }
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private HimmelskoerperTab _HimmelskoerperTab;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
