//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileSysASMX.Client.ASMX {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FSysItem", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FileSysASMX.Client.ASMX.File))]
    [System.Runtime.Serialization.KnownTypeAttribute(typeof(FileSysASMX.Client.ASMX.Dir))]
    public partial class FSysItem : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="File", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class File : FileSysASMX.Client.ASMX.FSysItem {
        
        private long SizeInBytesField;
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long SizeInBytes {
            get {
                return this.SizeInBytesField;
            }
            set {
                if ((this.SizeInBytesField.Equals(value) != true)) {
                    this.SizeInBytesField = value;
                    this.RaisePropertyChanged("SizeInBytes");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Dir", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Dir : FileSysASMX.Client.ASMX.FSysItem {
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<FileSysASMX.Client.ASMX.File> Files_ASMXField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.Collections.Generic.List<FileSysASMX.Client.ASMX.Dir> SubDirs_ASMXField;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<FileSysASMX.Client.ASMX.File> Files_ASMX {
            get {
                return this.Files_ASMXField;
            }
            set {
                if ((object.ReferenceEquals(this.Files_ASMXField, value) != true)) {
                    this.Files_ASMXField = value;
                    this.RaisePropertyChanged("Files_ASMX");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public System.Collections.Generic.List<FileSysASMX.Client.ASMX.Dir> SubDirs_ASMX {
            get {
                return this.SubDirs_ASMXField;
            }
            set {
                if ((object.ReferenceEquals(this.SubDirs_ASMXField, value) != true)) {
                    this.SubDirs_ASMXField = value;
                    this.RaisePropertyChanged("SubDirs_ASMX");
                }
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="FileSimple", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class FileSimple : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        private long SizeInBytesField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public long SizeInBytes {
            get {
                return this.SizeInBytesField;
            }
            set {
                if ((this.SizeInBytesField.Equals(value) != true)) {
                    this.SizeInBytesField = value;
                    this.RaisePropertyChanged("SizeInBytes");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ASMX.FileSysSoap")]
    public interface FileSysSoap {
        
        // CODEGEN: Generating message contract since element name subDir from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSubDirs", ReplyAction="*")]
        FileSysASMX.Client.ASMX.GetSubDirsResponse GetSubDirs(FileSysASMX.Client.ASMX.GetSubDirsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSubDirs", ReplyAction="*")]
        System.Threading.Tasks.Task<FileSysASMX.Client.ASMX.GetSubDirsResponse> GetSubDirsAsync(FileSysASMX.Client.ASMX.GetSubDirsRequest request);
        
        // CODEGEN: Generating message contract since element name subDir from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSubDirItems", ReplyAction="*")]
        FileSysASMX.Client.ASMX.GetSubDirItemsResponse GetSubDirItems(FileSysASMX.Client.ASMX.GetSubDirItemsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSubDirItems", ReplyAction="*")]
        System.Threading.Tasks.Task<FileSysASMX.Client.ASMX.GetSubDirItemsResponse> GetSubDirItemsAsync(FileSysASMX.Client.ASMX.GetSubDirItemsRequest request);
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileSimple", ReplyAction="*")]
        FileSysASMX.Client.ASMX.GetFileSimpleResponse GetFileSimple(FileSysASMX.Client.ASMX.GetFileSimpleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetFileSimple", ReplyAction="*")]
        System.Threading.Tasks.Task<FileSysASMX.Client.ASMX.GetFileSimpleResponse> GetFileSimpleAsync(FileSysASMX.Client.ASMX.GetFileSimpleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubDirsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubDirs", Namespace="http://tempuri.org/", Order=0)]
        public FileSysASMX.Client.ASMX.GetSubDirsRequestBody Body;
        
        public GetSubDirsRequest() {
        }
        
        public GetSubDirsRequest(FileSysASMX.Client.ASMX.GetSubDirsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSubDirsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string subDir;
        
        public GetSubDirsRequestBody() {
        }
        
        public GetSubDirsRequestBody(string subDir) {
            this.subDir = subDir;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubDirsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubDirsResponse", Namespace="http://tempuri.org/", Order=0)]
        public FileSysASMX.Client.ASMX.GetSubDirsResponseBody Body;
        
        public GetSubDirsResponse() {
        }
        
        public GetSubDirsResponse(FileSysASMX.Client.ASMX.GetSubDirsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSubDirsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FileSysASMX.Client.ASMX.Dir GetSubDirsResult;
        
        public GetSubDirsResponseBody() {
        }
        
        public GetSubDirsResponseBody(FileSysASMX.Client.ASMX.Dir GetSubDirsResult) {
            this.GetSubDirsResult = GetSubDirsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubDirItemsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubDirItems", Namespace="http://tempuri.org/", Order=0)]
        public FileSysASMX.Client.ASMX.GetSubDirItemsRequestBody Body;
        
        public GetSubDirItemsRequest() {
        }
        
        public GetSubDirItemsRequest(FileSysASMX.Client.ASMX.GetSubDirItemsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSubDirItemsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string subDir;
        
        public GetSubDirItemsRequestBody() {
        }
        
        public GetSubDirItemsRequestBody(string subDir) {
            this.subDir = subDir;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSubDirItemsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSubDirItemsResponse", Namespace="http://tempuri.org/", Order=0)]
        public FileSysASMX.Client.ASMX.GetSubDirItemsResponseBody Body;
        
        public GetSubDirItemsResponse() {
        }
        
        public GetSubDirItemsResponse(FileSysASMX.Client.ASMX.GetSubDirItemsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSubDirItemsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public System.Collections.Generic.List<FileSysASMX.Client.ASMX.FSysItem> GetSubDirItemsResult;
        
        public GetSubDirItemsResponseBody() {
        }
        
        public GetSubDirItemsResponseBody(System.Collections.Generic.List<FileSysASMX.Client.ASMX.FSysItem> GetSubDirItemsResult) {
            this.GetSubDirItemsResult = GetSubDirItemsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileSimpleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileSimple", Namespace="http://tempuri.org/", Order=0)]
        public FileSysASMX.Client.ASMX.GetFileSimpleRequestBody Body;
        
        public GetFileSimpleRequest() {
        }
        
        public GetFileSimpleRequest(FileSysASMX.Client.ASMX.GetFileSimpleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileSimpleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public GetFileSimpleRequestBody() {
        }
        
        public GetFileSimpleRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetFileSimpleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetFileSimpleResponse", Namespace="http://tempuri.org/", Order=0)]
        public FileSysASMX.Client.ASMX.GetFileSimpleResponseBody Body;
        
        public GetFileSimpleResponse() {
        }
        
        public GetFileSimpleResponse(FileSysASMX.Client.ASMX.GetFileSimpleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetFileSimpleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FileSysASMX.Client.ASMX.FileSimple GetFileSimpleResult;
        
        public GetFileSimpleResponseBody() {
        }
        
        public GetFileSimpleResponseBody(FileSysASMX.Client.ASMX.FileSimple GetFileSimpleResult) {
            this.GetFileSimpleResult = GetFileSimpleResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface FileSysSoapChannel : FileSysASMX.Client.ASMX.FileSysSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileSysSoapClient : System.ServiceModel.ClientBase<FileSysASMX.Client.ASMX.FileSysSoap>, FileSysASMX.Client.ASMX.FileSysSoap {
        
        public FileSysSoapClient() {
        }
        
        public FileSysSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileSysSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileSysSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileSysSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileSysASMX.Client.ASMX.GetSubDirsResponse FileSysASMX.Client.ASMX.FileSysSoap.GetSubDirs(FileSysASMX.Client.ASMX.GetSubDirsRequest request) {
            return base.Channel.GetSubDirs(request);
        }
        
        public FileSysASMX.Client.ASMX.Dir GetSubDirs(string subDir) {
            FileSysASMX.Client.ASMX.GetSubDirsRequest inValue = new FileSysASMX.Client.ASMX.GetSubDirsRequest();
            inValue.Body = new FileSysASMX.Client.ASMX.GetSubDirsRequestBody();
            inValue.Body.subDir = subDir;
            FileSysASMX.Client.ASMX.GetSubDirsResponse retVal = ((FileSysASMX.Client.ASMX.FileSysSoap)(this)).GetSubDirs(inValue);
            return retVal.Body.GetSubDirsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileSysASMX.Client.ASMX.GetSubDirsResponse> FileSysASMX.Client.ASMX.FileSysSoap.GetSubDirsAsync(FileSysASMX.Client.ASMX.GetSubDirsRequest request) {
            return base.Channel.GetSubDirsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileSysASMX.Client.ASMX.GetSubDirsResponse> GetSubDirsAsync(string subDir) {
            FileSysASMX.Client.ASMX.GetSubDirsRequest inValue = new FileSysASMX.Client.ASMX.GetSubDirsRequest();
            inValue.Body = new FileSysASMX.Client.ASMX.GetSubDirsRequestBody();
            inValue.Body.subDir = subDir;
            return ((FileSysASMX.Client.ASMX.FileSysSoap)(this)).GetSubDirsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileSysASMX.Client.ASMX.GetSubDirItemsResponse FileSysASMX.Client.ASMX.FileSysSoap.GetSubDirItems(FileSysASMX.Client.ASMX.GetSubDirItemsRequest request) {
            return base.Channel.GetSubDirItems(request);
        }
        
        public System.Collections.Generic.List<FileSysASMX.Client.ASMX.FSysItem> GetSubDirItems(string subDir) {
            FileSysASMX.Client.ASMX.GetSubDirItemsRequest inValue = new FileSysASMX.Client.ASMX.GetSubDirItemsRequest();
            inValue.Body = new FileSysASMX.Client.ASMX.GetSubDirItemsRequestBody();
            inValue.Body.subDir = subDir;
            FileSysASMX.Client.ASMX.GetSubDirItemsResponse retVal = ((FileSysASMX.Client.ASMX.FileSysSoap)(this)).GetSubDirItems(inValue);
            return retVal.Body.GetSubDirItemsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileSysASMX.Client.ASMX.GetSubDirItemsResponse> FileSysASMX.Client.ASMX.FileSysSoap.GetSubDirItemsAsync(FileSysASMX.Client.ASMX.GetSubDirItemsRequest request) {
            return base.Channel.GetSubDirItemsAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileSysASMX.Client.ASMX.GetSubDirItemsResponse> GetSubDirItemsAsync(string subDir) {
            FileSysASMX.Client.ASMX.GetSubDirItemsRequest inValue = new FileSysASMX.Client.ASMX.GetSubDirItemsRequest();
            inValue.Body = new FileSysASMX.Client.ASMX.GetSubDirItemsRequestBody();
            inValue.Body.subDir = subDir;
            return ((FileSysASMX.Client.ASMX.FileSysSoap)(this)).GetSubDirItemsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FileSysASMX.Client.ASMX.GetFileSimpleResponse FileSysASMX.Client.ASMX.FileSysSoap.GetFileSimple(FileSysASMX.Client.ASMX.GetFileSimpleRequest request) {
            return base.Channel.GetFileSimple(request);
        }
        
        public FileSysASMX.Client.ASMX.FileSimple GetFileSimple(string name) {
            FileSysASMX.Client.ASMX.GetFileSimpleRequest inValue = new FileSysASMX.Client.ASMX.GetFileSimpleRequest();
            inValue.Body = new FileSysASMX.Client.ASMX.GetFileSimpleRequestBody();
            inValue.Body.name = name;
            FileSysASMX.Client.ASMX.GetFileSimpleResponse retVal = ((FileSysASMX.Client.ASMX.FileSysSoap)(this)).GetFileSimple(inValue);
            return retVal.Body.GetFileSimpleResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FileSysASMX.Client.ASMX.GetFileSimpleResponse> FileSysASMX.Client.ASMX.FileSysSoap.GetFileSimpleAsync(FileSysASMX.Client.ASMX.GetFileSimpleRequest request) {
            return base.Channel.GetFileSimpleAsync(request);
        }
        
        public System.Threading.Tasks.Task<FileSysASMX.Client.ASMX.GetFileSimpleResponse> GetFileSimpleAsync(string name) {
            FileSysASMX.Client.ASMX.GetFileSimpleRequest inValue = new FileSysASMX.Client.ASMX.GetFileSimpleRequest();
            inValue.Body = new FileSysASMX.Client.ASMX.GetFileSimpleRequestBody();
            inValue.Body.name = name;
            return ((FileSysASMX.Client.ASMX.FileSysSoap)(this)).GetFileSimpleAsync(inValue);
        }
    }
}
