//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeplerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class HimmelskoerperTab
    {
        public HimmelskoerperTab()
        {
            this.UrlSammlungenTab = new HashSet<UrlSammlungenTab>();
            this.UmlaufbahnenTab1 = new HashSet<UmlaufbahnenTab>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public double Masse_in_kg { get; set; }
        public int HimmelskoerperTyp_ID { get; set; }
    
        public virtual RaumschiffeTab RaumschiffeTab { get; set; }
        public virtual Sterne_Planeten_MondeTab Sterne_Planeten_MondeTab { get; set; }
        public virtual HimmelskoerperTypenTab HimmelskoerperTypenTab { get; set; }
        public virtual ICollection<UrlSammlungenTab> UrlSammlungenTab { get; set; }
        public virtual UmlaufbahnenTab UmlaufbahnenTab { get; set; }
        public virtual ICollection<UmlaufbahnenTab> UmlaufbahnenTab1 { get; set; }
    }
}
