//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeplerDB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KeplerDBEntities : DbContext
    {
        public KeplerDBEntities()
            : base("name=KeplerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AufgabenTab> AufgabenTab { get; set; }
        public virtual DbSet<HimmelskoerperTab> HimmelskoerperTab { get; set; }
        public virtual DbSet<HimmelskoerperTypenTab> HimmelskoerperTypenTab { get; set; }
        public virtual DbSet<LaenderTab> LaenderTab { get; set; }
        public virtual DbSet<RaumschiffeTab> RaumschiffeTab { get; set; }
        public virtual DbSet<Sterne_Planeten_MondeTab> Sterne_Planeten_MondeTab { get; set; }
        public virtual DbSet<UmlaufbahnenTab> UmlaufbahnenTab { get; set; }
        public virtual DbSet<UrlSammlungenTab> UrlSammlungenTab { get; set; }
        public virtual DbSet<NatuerlicheHimmelskoerper> NatuerlicheHimmelskoerper { get; set; }
    }
}
