//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeplerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class NatuerlicheHimmelskoerper
    {
        public string Name { get; set; }
        public Nullable<double> Masse_in_Erdmassen { get; set; }
        public double Aequatordurchmesser_in_km { get; set; }
        public double Polardurchmesser_in_km { get; set; }
        public double Oberflaechentemperatur_in_K { get; set; }
        public Nullable<double> Jahr_in_Erdjahren { get; set; }
        public double Tag_in_h { get; set; }
        public double Fallbeschleunigung_in_meter_pro_sec { get; set; }
        public double Rotationsachsenneigung_in_Grad { get; set; }
    }
}
