//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KeplerDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UrlSammlungenTab
    {
        public int ID { get; set; }
        public string Kurzbeschreibung { get; set; }
        public string Url { get; set; }
        public int UrlTyp { get; set; }
        public int Himmelskoerper_ID { get; set; }
    
        public virtual HimmelskoerperTab HimmelskoerperTab { get; set; }
    }
}
