//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FileSysASMX.Client.SVC {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SVC.IFileSysWcf")]
    public interface IFileSysWcf {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSysWcf/GetSubDirs", ReplyAction="http://tempuri.org/IFileSysWcf/GetSubDirsResponse")]
        mko.FileSys.Dir GetSubDirs(string subDir);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IFileSysWcf/GetSubDirs", ReplyAction="http://tempuri.org/IFileSysWcf/GetSubDirsResponse")]
        System.Threading.Tasks.Task<mko.FileSys.Dir> GetSubDirsAsync(string subDir);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IFileSysWcfChannel : FileSysASMX.Client.SVC.IFileSysWcf, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class FileSysWcfClient : System.ServiceModel.ClientBase<FileSysASMX.Client.SVC.IFileSysWcf>, FileSysASMX.Client.SVC.IFileSysWcf {
        
        public FileSysWcfClient() {
        }
        
        public FileSysWcfClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public FileSysWcfClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileSysWcfClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public FileSysWcfClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public mko.FileSys.Dir GetSubDirs(string subDir) {
            return base.Channel.GetSubDirs(subDir);
        }
        
        public System.Threading.Tasks.Task<mko.FileSys.Dir> GetSubDirsAsync(string subDir) {
            return base.Channel.GetSubDirsAsync(subDir);
        }
    }
}
