//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceHost
{
    using System;
    using System.Collections.Generic;
    
    public partial class HimmelskoerperTab
    {
        public HimmelskoerperTab()
        {
            this.RaumschiffeTab = new HashSet<RaumschiffeTab>();
            this.Sterne_Planeten_MondeTab = new HashSet<Sterne_Planeten_MondeTab>();
            this.UrlSammlungenTab = new HashSet<UrlSammlungenTab>();
            this.UmlaufbahnenTab = new HashSet<UmlaufbahnenTab>();
            this.UmlaufbahnenTab1 = new HashSet<UmlaufbahnenTab>();
        }
    
        public int ID { get; set; }
        public string Name { get; set; }
        public double Masse_in_kg { get; set; }
        public int HimmelskoerperTyp_ID { get; set; }
    
        public virtual HimmelskoerperTypenTab HimmelskoerperTypenTab { get; set; }
        public virtual ICollection<RaumschiffeTab> RaumschiffeTab { get; set; }
        public virtual ICollection<Sterne_Planeten_MondeTab> Sterne_Planeten_MondeTab { get; set; }
        public virtual ICollection<UrlSammlungenTab> UrlSammlungenTab { get; set; }
        public virtual ICollection<UmlaufbahnenTab> UmlaufbahnenTab { get; set; }
        public virtual ICollection<UmlaufbahnenTab> UmlaufbahnenTab1 { get; set; }
    }
}
