//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WcfDataServiceHost
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class KeplerDBEntities : DbContext
    {
        public KeplerDBEntities()
            : base("name=KeplerDBEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<HimmelskoerperTab> HimmelskoerperTab { get; set; }
        public DbSet<HimmelskoerperTypenTab> HimmelskoerperTypenTab { get; set; }
        public DbSet<LaenderTab> LaenderTab { get; set; }
        public DbSet<RaumschiffAufgabenTab> RaumschiffAufgabenTab { get; set; }
        public DbSet<RaumschiffeTab> RaumschiffeTab { get; set; }
        public DbSet<Sterne_Planeten_MondeTab> Sterne_Planeten_MondeTab { get; set; }
        public DbSet<UmlaufbahnenTab> UmlaufbahnenTab { get; set; }
        public DbSet<UrlSammlungenTab> UrlSammlungenTab { get; set; }
    }
}
