//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// Name der Ursprungsdatei:
// Erstellungsdatum: 04.06.2014 22:53:35
namespace WcfTestLibClient.FileFeaturesDbDataServiceRef
{
    
    /// <summary>
    /// Es gibt keine Kommentare für FileFeaturesDbEntities im Schema.
    /// </summary>
    public partial class FileFeaturesDbEntities : global::System.Data.Services.Client.DataServiceContext
    {
        /// <summary>
        /// Initialisiert ein neues FileFeaturesDbEntities-Objekt.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public FileFeaturesDbEntities(global::System.Uri serviceRoot) : 
                base(serviceRoot)
        {
            this.ResolveName = new global::System.Func<global::System.Type, string>(this.ResolveNameFromType);
            this.ResolveType = new global::System.Func<string, global::System.Type>(this.ResolveTypeFromName);
            this.OnContextCreated();
        }
        partial void OnContextCreated();
        /// <summary>
        /// Da sich der Namespace, der für diesen Dienstverweis
        ///  in Visual Studio konfiguriert ist, von demjenigen unterscheidet, der in dem 
        /// Server-Schema angegeben ist, verwenden Sie Typemapper, um Zuordnungen zwischen den beiden vorzunehmen.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected global::System.Type ResolveTypeFromName(string typeName)
        {
            if (typeName.StartsWith("FileFeaturesDbModel", global::System.StringComparison.Ordinal))
            {
                return this.GetType().Assembly.GetType(string.Concat("WcfTestLibClient.FileFeaturesDbDataServiceRef", typeName.Substring(19)), false);
            }
            return null;
        }
        /// <summary>
        /// Da sich der Namespace, der für diesen Dienstverweis
        ///  in Visual Studio konfiguriert ist, von demjenigen unterscheidet, der in dem 
        /// Server-Schema angegeben ist, verwenden Sie Typemapper, um Zuordnungen zwischen den beiden vorzunehmen.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected string ResolveNameFromType(global::System.Type clientType)
        {
            if (clientType.Namespace.Equals("WcfTestLibClient.FileFeaturesDbDataServiceRef", global::System.StringComparison.Ordinal))
            {
                return string.Concat("FileFeaturesDbModel.", clientType.Name);
            }
            return null;
        }
        /// <summary>
        /// Es gibt keine Kommentare für BasicFeatures im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<BasicFeature> BasicFeatures
        {
            get
            {
                if ((this._BasicFeatures == null))
                {
                    this._BasicFeatures = base.CreateQuery<BasicFeature>("BasicFeatures");
                }
                return this._BasicFeatures;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<BasicFeature> _BasicFeatures;
        /// <summary>
        /// Es gibt keine Kommentare für FileClasses im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<FileClass> FileClasses
        {
            get
            {
                if ((this._FileClasses == null))
                {
                    this._FileClasses = base.CreateQuery<FileClass>("FileClasses");
                }
                return this._FileClasses;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<FileClass> _FileClasses;
        /// <summary>
        /// Es gibt keine Kommentare für FilePaths im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<FilePath> FilePaths
        {
            get
            {
                if ((this._FilePaths == null))
                {
                    this._FilePaths = base.CreateQuery<FilePath>("FilePaths");
                }
                return this._FilePaths;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<FilePath> _FilePaths;
        /// <summary>
        /// Es gibt keine Kommentare für Files im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<File> Files
        {
            get
            {
                if ((this._Files == null))
                {
                    this._Files = base.CreateQuery<File>("Files");
                }
                return this._Files;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<File> _Files;
        /// <summary>
        /// Es gibt keine Kommentare für images im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceQuery<image> images
        {
            get
            {
                if ((this._images == null))
                {
                    this._images = base.CreateQuery<image>("images");
                }
                return this._images;
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceQuery<image> _images;
        /// <summary>
        /// Es gibt keine Kommentare für BasicFeatures im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToBasicFeatures(BasicFeature basicFeature)
        {
            base.AddObject("BasicFeatures", basicFeature);
        }
        /// <summary>
        /// Es gibt keine Kommentare für FileClasses im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFileClasses(FileClass fileClass)
        {
            base.AddObject("FileClasses", fileClass);
        }
        /// <summary>
        /// Es gibt keine Kommentare für FilePaths im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFilePaths(FilePath filePath)
        {
            base.AddObject("FilePaths", filePath);
        }
        /// <summary>
        /// Es gibt keine Kommentare für Files im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToFiles(File file)
        {
            base.AddObject("Files", file);
        }
        /// <summary>
        /// Es gibt keine Kommentare für images im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public void AddToimages(image image)
        {
            base.AddObject("images", image);
        }
    }
    /// <summary>
    /// Es gibt keine Kommentare für FileFeaturesDbModel.BasicFeature im Schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("BasicFeatures")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class BasicFeature : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues BasicFeature-Objekt.
        /// </summary>
        /// <param name="ID">Anfangswert von id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static BasicFeature CreateBasicFeature(int ID)
        {
            BasicFeature basicFeature = new BasicFeature();
            basicFeature.id = ID;
            return basicFeature;
        }
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft id im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft fkey_id_files im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> fkey_id_files
        {
            get
            {
                return this._fkey_id_files;
            }
            set
            {
                this.Onfkey_id_filesChanging(value);
                this._fkey_id_files = value;
                this.Onfkey_id_filesChanged();
                this.OnPropertyChanged("fkey_id_files");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _fkey_id_files;
        partial void Onfkey_id_filesChanging(global::System.Nullable<int> value);
        partial void Onfkey_id_filesChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft LastAccesssTime im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> LastAccesssTime
        {
            get
            {
                return this._LastAccesssTime;
            }
            set
            {
                this.OnLastAccesssTimeChanging(value);
                this._LastAccesssTime = value;
                this.OnLastAccesssTimeChanged();
                this.OnPropertyChanged("LastAccesssTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _LastAccesssTime;
        partial void OnLastAccesssTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnLastAccesssTimeChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft LastWriteTime im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> LastWriteTime
        {
            get
            {
                return this._LastWriteTime;
            }
            set
            {
                this.OnLastWriteTimeChanging(value);
                this._LastWriteTime = value;
                this.OnLastWriteTimeChanged();
                this.OnPropertyChanged("LastWriteTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _LastWriteTime;
        partial void OnLastWriteTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnLastWriteTimeChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft CreationTime im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<global::System.DateTime> CreationTime
        {
            get
            {
                return this._CreationTime;
            }
            set
            {
                this.OnCreationTimeChanging(value);
                this._CreationTime = value;
                this.OnCreationTimeChanged();
                this.OnPropertyChanged("CreationTime");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<global::System.DateTime> _CreationTime;
        partial void OnCreationTimeChanging(global::System.Nullable<global::System.DateTime> value);
        partial void OnCreationTimeChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft SizeInBytes im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<long> SizeInBytes
        {
            get
            {
                return this._SizeInBytes;
            }
            set
            {
                this.OnSizeInBytesChanging(value);
                this._SizeInBytes = value;
                this.OnSizeInBytesChanged();
                this.OnPropertyChanged("SizeInBytes");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<long> _SizeInBytes;
        partial void OnSizeInBytesChanging(global::System.Nullable<long> value);
        partial void OnSizeInBytesChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft fkey_FileClass im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> fkey_FileClass
        {
            get
            {
                return this._fkey_FileClass;
            }
            set
            {
                this.Onfkey_FileClassChanging(value);
                this._fkey_FileClass = value;
                this.Onfkey_FileClassChanged();
                this.OnPropertyChanged("fkey_FileClass");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _fkey_FileClass;
        partial void Onfkey_FileClassChanging(global::System.Nullable<int> value);
        partial void Onfkey_FileClassChanged();
        /// <summary>
        /// Es gibt keine Kommentare für FileClass im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public FileClass FileClass
        {
            get
            {
                return this._FileClass;
            }
            set
            {
                this._FileClass = value;
                this.OnPropertyChanged("FileClass");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private FileClass _FileClass;
        /// <summary>
        /// Es gibt keine Kommentare für File im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public File File
        {
            get
            {
                return this._File;
            }
            set
            {
                this._File = value;
                this.OnPropertyChanged("File");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private File _File;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Es gibt keine Kommentare für FileFeaturesDbModel.FileClass im Schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("FileClasses")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class FileClass : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues FileClass-Objekt.
        /// </summary>
        /// <param name="ID">Anfangswert von id.</param>
        /// <param name="name">Anfangswert von name.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static FileClass CreateFileClass(int ID, string name)
        {
            FileClass fileClass = new FileClass();
            fileClass.id = ID;
            fileClass.name = name;
            return fileClass;
        }
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft id im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft name im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string name
        {
            get
            {
                return this._name;
            }
            set
            {
                this.OnnameChanging(value);
                this._name = value;
                this.OnnameChanged();
                this.OnPropertyChanged("name");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _name;
        partial void OnnameChanging(string value);
        partial void OnnameChanged();
        /// <summary>
        /// Es gibt keine Kommentare für BasicFeatures im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<BasicFeature> BasicFeatures
        {
            get
            {
                return this._BasicFeatures;
            }
            set
            {
                this._BasicFeatures = value;
                this.OnPropertyChanged("BasicFeatures");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<BasicFeature> _BasicFeatures = new global::System.Data.Services.Client.DataServiceCollection<BasicFeature>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Es gibt keine Kommentare für FileFeaturesDbModel.FilePath im Schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("FilePaths")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class FilePath : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues FilePath-Objekt.
        /// </summary>
        /// <param name="ID">Anfangswert von id.</param>
        /// <param name="path">Anfangswert von path.</param>
        /// <param name="uid">Anfangswert von uid.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static FilePath CreateFilePath(int ID, string path, global::System.Guid uid)
        {
            FilePath filePath = new FilePath();
            filePath.id = ID;
            filePath.path = path;
            filePath.uid = uid;
            return filePath;
        }
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft id im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft path im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string path
        {
            get
            {
                return this._path;
            }
            set
            {
                this.OnpathChanging(value);
                this._path = value;
                this.OnpathChanged();
                this.OnPropertyChanged("path");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _path;
        partial void OnpathChanging(string value);
        partial void OnpathChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft uid im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid uid
        {
            get
            {
                return this._uid;
            }
            set
            {
                this.OnuidChanging(value);
                this._uid = value;
                this.OnuidChanged();
                this.OnPropertyChanged("uid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _uid;
        partial void OnuidChanging(global::System.Guid value);
        partial void OnuidChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Dirs im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<File> Dirs
        {
            get
            {
                return this._Dirs;
            }
            set
            {
                this._Dirs = value;
                this.OnPropertyChanged("Dirs");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<File> _Dirs = new global::System.Data.Services.Client.DataServiceCollection<File>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// Es gibt keine Kommentare für Files im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<File> Files
        {
            get
            {
                return this._Files;
            }
            set
            {
                this._Files = value;
                this.OnPropertyChanged("Files");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<File> _Files = new global::System.Data.Services.Client.DataServiceCollection<File>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// Es gibt keine Kommentare für SuperDirs im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<File> SuperDirs
        {
            get
            {
                return this._SuperDirs;
            }
            set
            {
                this._SuperDirs = value;
                this.OnPropertyChanged("SuperDirs");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<File> _SuperDirs = new global::System.Data.Services.Client.DataServiceCollection<File>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Es gibt keine Kommentare für FileFeaturesDbModel.File im Schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("Files")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class File : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues File-Objekt.
        /// </summary>
        /// <param name="ID">Anfangswert von id.</param>
        /// <param name="file_uid">Anfangswert von file_uid.</param>
        /// <param name="dir_uid">Anfangswert von dir_uid.</param>
        /// <param name="super_dir_uid">Anfangswert von super_dir_uid.</param>
        /// <param name="fkey_file_id">Anfangswert von fkey_file_id.</param>
        /// <param name="fkey_dir_id">Anfangswert von fkey_dir_id.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static File CreateFile(int ID, global::System.Guid file_uid, global::System.Guid dir_uid, global::System.Guid super_dir_uid, int fkey_file_id, int fkey_dir_id)
        {
            File file = new File();
            file.id = ID;
            file.file_uid = file_uid;
            file.dir_uid = dir_uid;
            file.super_dir_uid = super_dir_uid;
            file.fkey_file_id = fkey_file_id;
            file.fkey_dir_id = fkey_dir_id;
            return file;
        }
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft id im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft file_uid im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid file_uid
        {
            get
            {
                return this._file_uid;
            }
            set
            {
                this.Onfile_uidChanging(value);
                this._file_uid = value;
                this.Onfile_uidChanged();
                this.OnPropertyChanged("file_uid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _file_uid;
        partial void Onfile_uidChanging(global::System.Guid value);
        partial void Onfile_uidChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft dir_uid im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid dir_uid
        {
            get
            {
                return this._dir_uid;
            }
            set
            {
                this.Ondir_uidChanging(value);
                this._dir_uid = value;
                this.Ondir_uidChanged();
                this.OnPropertyChanged("dir_uid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _dir_uid;
        partial void Ondir_uidChanging(global::System.Guid value);
        partial void Ondir_uidChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft super_dir_uid im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Guid super_dir_uid
        {
            get
            {
                return this._super_dir_uid;
            }
            set
            {
                this.Onsuper_dir_uidChanging(value);
                this._super_dir_uid = value;
                this.Onsuper_dir_uidChanged();
                this.OnPropertyChanged("super_dir_uid");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Guid _super_dir_uid;
        partial void Onsuper_dir_uidChanging(global::System.Guid value);
        partial void Onsuper_dir_uidChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft fkey_file_id im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int fkey_file_id
        {
            get
            {
                return this._fkey_file_id;
            }
            set
            {
                this.Onfkey_file_idChanging(value);
                this._fkey_file_id = value;
                this.Onfkey_file_idChanged();
                this.OnPropertyChanged("fkey_file_id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _fkey_file_id;
        partial void Onfkey_file_idChanging(int value);
        partial void Onfkey_file_idChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft fkey_dir_id im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int fkey_dir_id
        {
            get
            {
                return this._fkey_dir_id;
            }
            set
            {
                this.Onfkey_dir_idChanging(value);
                this._fkey_dir_id = value;
                this.Onfkey_dir_idChanged();
                this.OnPropertyChanged("fkey_dir_id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _fkey_dir_id;
        partial void Onfkey_dir_idChanging(int value);
        partial void Onfkey_dir_idChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft fkey_super_dir_id im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Nullable<int> fkey_super_dir_id
        {
            get
            {
                return this._fkey_super_dir_id;
            }
            set
            {
                this.Onfkey_super_dir_idChanging(value);
                this._fkey_super_dir_id = value;
                this.Onfkey_super_dir_idChanged();
                this.OnPropertyChanged("fkey_super_dir_id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Nullable<int> _fkey_super_dir_id;
        partial void Onfkey_super_dir_idChanging(global::System.Nullable<int> value);
        partial void Onfkey_super_dir_idChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft filename im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string filename
        {
            get
            {
                return this._filename;
            }
            set
            {
                this.OnfilenameChanging(value);
                this._filename = value;
                this.OnfilenameChanged();
                this.OnPropertyChanged("filename");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _filename;
        partial void OnfilenameChanging(string value);
        partial void OnfilenameChanged();
        /// <summary>
        /// Es gibt keine Kommentare für BasicFeatures im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<BasicFeature> BasicFeatures
        {
            get
            {
                return this._BasicFeatures;
            }
            set
            {
                this._BasicFeatures = value;
                this.OnPropertyChanged("BasicFeatures");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<BasicFeature> _BasicFeatures = new global::System.Data.Services.Client.DataServiceCollection<BasicFeature>(null, System.Data.Services.Client.TrackingMode.None);
        /// <summary>
        /// Es gibt keine Kommentare für Dir im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public FilePath Dir
        {
            get
            {
                return this._Dir;
            }
            set
            {
                this._Dir = value;
                this.OnPropertyChanged("Dir");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private FilePath _Dir;
        /// <summary>
        /// Es gibt keine Kommentare für FilePath im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public FilePath FilePath
        {
            get
            {
                return this._FilePath;
            }
            set
            {
                this._FilePath = value;
                this.OnPropertyChanged("FilePath");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private FilePath _FilePath;
        /// <summary>
        /// Es gibt keine Kommentare für Superdir im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public FilePath Superdir
        {
            get
            {
                return this._Superdir;
            }
            set
            {
                this._Superdir = value;
                this.OnPropertyChanged("Superdir");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private FilePath _Superdir;
        /// <summary>
        /// Es gibt keine Kommentare für images im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public global::System.Data.Services.Client.DataServiceCollection<image> images
        {
            get
            {
                return this._images;
            }
            set
            {
                this._images = value;
                this.OnPropertyChanged("images");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private global::System.Data.Services.Client.DataServiceCollection<image> _images = new global::System.Data.Services.Client.DataServiceCollection<image>(null, System.Data.Services.Client.TrackingMode.None);
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
    /// <summary>
    /// Es gibt keine Kommentare für FileFeaturesDbModel.image im Schema.
    /// </summary>
    /// <KeyProperties>
    /// id
    /// </KeyProperties>
    [global::System.Data.Services.Common.EntitySetAttribute("images")]
    [global::System.Data.Services.Common.DataServiceKeyAttribute("id")]
    public partial class image : global::System.ComponentModel.INotifyPropertyChanged
    {
        /// <summary>
        /// Erstellt ein neues image-Objekt.
        /// </summary>
        /// <param name="ID">Anfangswert von id.</param>
        /// <param name="fkey_id_files">Anfangswert von fkey_id_files.</param>
        /// <param name="description">Anfangswert von description.</param>
        /// <param name="img">Anfangswert von img.</param>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public static image Createimage(int ID, int fkey_id_files, string description, byte[] img)
        {
            image image = new image();
            image.id = ID;
            image.fkey_id_files = fkey_id_files;
            image.description = description;
            image.img = img;
            return image;
        }
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft id im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int id
        {
            get
            {
                return this._id;
            }
            set
            {
                this.OnidChanging(value);
                this._id = value;
                this.OnidChanged();
                this.OnPropertyChanged("id");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _id;
        partial void OnidChanging(int value);
        partial void OnidChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft fkey_id_files im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public int fkey_id_files
        {
            get
            {
                return this._fkey_id_files;
            }
            set
            {
                this.Onfkey_id_filesChanging(value);
                this._fkey_id_files = value;
                this.Onfkey_id_filesChanged();
                this.OnPropertyChanged("fkey_id_files");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private int _fkey_id_files;
        partial void Onfkey_id_filesChanging(int value);
        partial void Onfkey_id_filesChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft description im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public string description
        {
            get
            {
                return this._description;
            }
            set
            {
                this.OndescriptionChanging(value);
                this._description = value;
                this.OndescriptionChanged();
                this.OnPropertyChanged("description");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private string _description;
        partial void OndescriptionChanging(string value);
        partial void OndescriptionChanged();
        /// <summary>
        /// Es gibt keine Kommentare für Eigenschaft img im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public byte[] img
        {
            get
            {
                if ((this._img != null))
                {
                    return ((byte[])(this._img.Clone()));
                }
                else
                {
                    return null;
                }
            }
            set
            {
                this.OnimgChanging(value);
                this._img = value;
                this.OnimgChanged();
                this.OnPropertyChanged("img");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private byte[] _img;
        partial void OnimgChanging(byte[] value);
        partial void OnimgChanged();
        /// <summary>
        /// Es gibt keine Kommentare für File im Schema.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public File File
        {
            get
            {
                return this._File;
            }
            set
            {
                this._File = value;
                this.OnPropertyChanged("File");
            }
        }
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        private File _File;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        public event global::System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Services.Design", "1.0.0")]
        protected virtual void OnPropertyChanged(string property)
        {
            if ((this.PropertyChanged != null))
            {
                this.PropertyChanged(this, new global::System.ComponentModel.PropertyChangedEventArgs(property));
            }
        }
    }
}
